name: tfswitch
version: git
summary: A command line tool to switch between different versions of terraform
description: |
  The `tfswitch` command line tool lets you switch between different versions of terraform(https://www.terraform.io/).
  If you do not have a particular version of terraform installed, `tfswitch` will download the version you desire.
  The installation is minimal and easy.
  Once installed, simply select the version you require from the dropdown and start using terraform.
architectures:
  - build-on: arm64
  - build-on: amd64
assumes: [snapd2.45]
base: core18

grade: stable
confinement: strict
license: MPL-2.0

apps:
  tfswitch:
    command: bin/tfswitch
    plugs:
      - home
      - network
      - network-bind
      
parts:
  tfswitch:
    source: https://github.com/versus/terraform-switcher.git
    plugin: go
    go-importpath: github.com/versus/terraform-switcher
    build-packages:
      - gcc-multilib
    go-buildtags:
      - tfswitch
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag | sort | tail -1)"
      snapcraftctl set-version `echo ${last_committed_tag} | sed "s/v//g"`
    override-build: 
      last_committed_tag="$(git tag | sort | tail -1)"
      go build -ldflags "-X main.version=$last_committed_tag" -o ../install/bin/tfswitch


